In [1]:
import numpy as np

aa = np.arange(15).reshape(3, 5)
print(aa)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(aa.shape)
print(aa.ndim)
print(aa.dtype.name)
print(aa.itemsize)
print(aa.size)

(3, 5)
2
int32
4
15


In [4]:
aa = np.array([6, 7, 8])

aa.dtype

dtype('int32')

In [5]:
aa = np.array([1., 2., 3.])
aa.dtype

dtype('float64')

In [9]:
bb = np.arange(9).reshape(3, 3)
print(bb)

for i in bb:
    print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]


In [11]:
bb.sum(axis=1)

array([ 3, 12, 21])

In [21]:
my_list = [i for i in range(10000000)]

print(sum(my_list))

49999995000000


In [20]:
my_gen = (i for i in range(10000000))

print(sum(my_gen))

49999995000000


In [24]:
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

print(fib(6))

8


In [25]:
class A:
    name = 'Alice'

o = A()
print(o.__dict__)
print(o.name)

{}
Alice


In [26]:
class Name:
    def __get__(self, obj, objtype):
        return "Peter"

class A:
    name = Name()

o = A()
print(o.name)

TypeError: Name.__get__() takes 0 positional arguments but 3 were given