In [1]:
import numpy as np

aa = np.arange(15).reshape(3, 5)
print(aa)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(aa.shape)
print(aa.ndim)
print(aa.dtype.name)
print(aa.itemsize)
print(aa.size)

(3, 5)
2
int32
4
15


In [4]:
aa = np.array([6, 7, 8])

aa.dtype

dtype('int32')

In [5]:
aa = np.array([1., 2., 3.])
aa.dtype

dtype('float64')

In [9]:
bb = np.arange(9).reshape(3, 3)
print(bb)

for i in bb:
    print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]


In [11]:
bb.sum(axis=1)

array([ 3, 12, 21])

In [21]:
my_list = [i for i in range(10000000)]

print(sum(my_list))

49999995000000


In [20]:
my_gen = (i for i in range(10000000))

print(sum(my_gen))

49999995000000


In [24]:
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

print(fib(6))

8


In [25]:
class A:
    name = 'Alice'

o = A()
print(o.__dict__)
print(o.name)

{}
Alice


In [29]:
class Name:
    def __get__(self, obj, objtype):
        return "Peter"

class A:
    name = Name()

o = A()
print(o.name)
o.name = 'John'
print(o.name)
Name.__set__= lambda x, y, z: None
print(o.name)

Peter
John
Peter


In [30]:
print(Name.__dict__)

{'__module__': '__main__', '__get__': <function Name.__get__ at 0x0000028ABC3467A0>, '__dict__': <attribute '__dict__' of 'Name' objects>, '__weakref__': <attribute '__weakref__' of 'Name' objects>, '__doc__': None, '__set__': <function <lambda> at 0x0000028ABC347A60>}


In [37]:
class A:
    nn = 'hh'
    def __init__(self, name) -> None:
        self.name = name
        # self.nn = 'my' + name


aa = A('a')
bb = A('b')

print(aa.nn)
print(bb.nn)
print(aa.name)
print(bb.name)
aa.nn = 'myaa'
print(aa.nn)

print(aa.__dict__)

hh
hh
a
b
myaa
{'name': 'a', 'nn': 'myaa'}


In [38]:
dir(aa)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'name',
 'nn']