In [1]:
import numpy as np

aa = np.arange(15).reshape(3, 5)
print(aa)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(aa.shape)
print(aa.ndim)
print(aa.dtype.name)
print(aa.itemsize)
print(aa.size)

(3, 5)
2
int32
4
15


In [4]:
aa = np.array([6, 7, 8])

aa.dtype

dtype('int32')

In [5]:
aa = np.array([1., 2., 3.])
aa.dtype

dtype('float64')

In [9]:
bb = np.arange(9).reshape(3, 3)
print(bb)

for i in bb:
    print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]


In [11]:
bb.sum(axis=1)

array([ 3, 12, 21])